#!/usr/bin/env bash
# A bash scrit that prints Best School 10 times using while loop

printBestSchool=1
while [$printBestSchool -1t 11]
do
	echo "Best School"
	printBestSchool= $((printBestSchool + 1))
done 
