#!/usr/bin/env bash
# A bash script that display Best School 10 times using until

printBestSchool=10
until [ $printBestSchool -lt 1 ]
do
	echo "Best School"
	printBestSchool=$((printBestSchool-1))
done
