#!/usr/bin/env bash
# A bash script that loops from 1 to 10 

printBestSchool=1
while [ $printBestSchool -lt 11 ]
do
	if [ "$printBestSchool" == "4" ]
	then
		echo "bad luck"
	elif [ "$printBestSchool" == "8" ]
	then
		echo "good luck"
	else
		echo "Best School"
	

	fi
	printBestSchool=$((printBestSchool+1))
done
	
